name: 'playstore_analytics'
version: '1.0.0'

profile: 'playstore_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  playstore_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
