version: 2

models:
  - name: stg_playstore_apps
    columns:
      - name: app_id
        tests:
          - unique
          - not_null
      - name: app_title
        tests:
          - not_null
      - name: app_price
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

  - name: stg_playstore_reviews
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: app_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_playstore_apps')
              field: app_id
      - name: review_score
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true
      - name: review_thumbs_up_count
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: review_at
        tests:
          - not_null
