version: 2

models:
  - name: dim_categories
    columns:
      - name: category_sk
        tests:
          - unique
          - not_null

  - name: dim_developers
    columns:
      - name: developer_sk
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: dim_apps
    columns:
      - name: app_sk
        tests:
          - unique
          - not_null
      - name: developer_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_developers')
              field: developer_sk
      - name: category_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_categories')
              field: category_sk
