version: 2

models:
  - name: fact_reviews
    columns:
      - name: review_natural_key
        tests:
          - unique
          - not_null
      - name: app_scd_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_apps_scd')
              field: app_scd_sk
      - name: review_date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: review_score
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
